In [1]:
%display latex

In [2]:
var('x,t')
implicit_multiplication(10)

In [3]:
R.<x, t> = PolynomialRing(QQ)
f = (x^6 - 5*x^4 + 6*x^2 - 1)*t^5 + (x^5 - 4*x^3 + 3*x^2)*t^6
g = x*t^2-x^2*t+x

h = f.quo_rem(g)
show(h[0])
show('\n')
show(h[1])

2*x^8 + 2*x^7*t + 2*x^6*t^2 + 2*x^5*t^3 + x^4*t^4 - 14*x^6 - 12*x^5*t - 10*x^4*t^2 - 9*x^3*t^3 - 4*x^2*t^4 + 3*x^5 + 3*x^4*t + 3*x^3*t^2 + 3*x^2*t^3 + 3*x*t^4 + 29*x^4 + 19*x^3*t + 10*x^2*t^2 + 6*x*t^3 - 9*x^3 - 6*x^2*t - 3*x*t^2 - 16*x^2 - 6*x*t + 3*x

'\n'

2*x^10*t - 2*x^9 - 16*x^8*t + 3*x^7*t + 14*x^7 + 41*x^6*t - 3*x^6 - 12*x^5*t - 29*x^5 - 35*x^4*t - t^5 + 9*x^4 + 9*x^3*t + 16*x^3 + 6*x^2*t - 3*x^2

In [6]:
p = f // g
p

2*x^8 + 2*x^7*t + 2*x^6*t^2 + 2*x^5*t^3 + x^4*t^4 - 14*x^6 - 12*x^5*t - 10*x^4*t^2 - 9*x^3*t^3 - 4*x^2*t^4 + 3*x^5 + 3*x^4*t + 3*x^3*t^2 + 3*x^2*t^3 + 3*x*t^4 + 29*x^4 + 19*x^3*t + 10*x^2*t^2 + 6*x*t^3 - 9*x^3 - 6*x^2*t - 3*x*t^2 - 16*x^2 - 6*x*t + 3*x

In [9]:
A = Matrix([[1,2],[7,4],[-1,2]])
b = vector([3,2,1])
show(A)
show(b)

[ 1  2]
[ 7  4]
[-1  2]

(3, 2, 1)

In [10]:
(A.T*A).rref()

[1 0]
[0 1]

In [11]:
(A.T * A)^(-1) * A.T * b

(-8/55, 46/55)

In [12]:
A = Matrix([[1,2,3],[3,2,1],[1,1,1]])
w = vector([1,1,-4])

In [13]:
A = Matrix([[2/3, 2/3, 1/3], [1/sqrt(2), -1/sqrt(2), 0]])

In [14]:
x = vector([1,2,2])
p = (A.T*A) *x
show(p-x)
(p-x) * (1/3)*vector([2,2,1])

(5/18, 5/18, -10/9)

0

In [15]:
A = Matrix(SR, [[-1,3], [1,5]])
show(A)

[-1  3]
[ 1  5]

In [16]:
a = A.columns()
abar = [v.normalized() for v in a]

In [20]:
show(a)
show(abar)

[(-1, 1), (3, 5)]

[(-1/2*sqrt(2), 1/2*sqrt(2)), (3/34*sqrt(34), 5/34*sqrt(34))]

In [21]:
def P(e,a):
    return (e*a)*(e.normalized())

In [22]:
u1 = (a[1] - P(u0, a[1])).normalized()
show(u1)

NameError: name 'u0' is not defined

In [23]:
vector([1,1])*vector([1,2])*vector([3,2])

(9, 6)

In [24]:
def GS(a):
    u = [None] * len(a)
    e = [None] * len(a)
    for k in range(len(a)):
        projs = [P(u[j], a[k]) for j in range(k)]
        show(k, projs)
        u[k] = (a[k] - sum(projs))
        e[k] = (u[k]).normalized()
    return (u, e)

In [25]:
A = Matrix(SR, [[12,-51,4], [6,167,-68],[-4,24,-41]])
show(A)
GS(A.columns())
print "done"

[ 12 -51   4]
[  6 167 -68]
[ -4  24 -41]

0 []

1 [(252, 126, -84)]

2 [(-168, -84, 56),
 (182406/1073*sqrt(2146), -24682/1073*sqrt(2146), -65016/1073*sqrt(2146))]

done


In [26]:
sum([3*vector([1,1]), -1*vector([1,2]), 2*vector([3,2])])

(8, 5)

In [27]:
u1bar = vector([12,6,-4]).normalized()

In [28]:
u1 = vector([12,6,-4])
a2 = vector([-51,167,24])
u1*a2

294

In [204]:
a2-(u1*a2)*u1bar

(-303, 41, 108)

In [212]:
A = Matrix([[-1,1],[1,1]])
A.T

[-1  1]
[ 1  1]

In [213]:
A * Matrix([[-1,3], [1,5]])

[2 2]
[0 8]

In [31]:
A = Matrix(SR, [[2,-2], [1,2]])
X = A.T * A
show(X)

[ 5 -2]
[-2  8]

In [40]:
A = Matrix(SR, [[2,-2], [1,-1]])
show(A)
show(A.kernel())

[ 2 -2]
[ 1 -1]

Vector space of degree 2 and dimension 1 over Symbolic Ring
Basis matrix:
[ 1 -2]

In [69]:
M = MatrixSpace(GF(5),5,7)
A = M([2,-1,-1,0,0,0,0,
       1,0,2,2,0,0,0,
       1,0,2,2,0,0,0,
       0,0,0,-1,2,-1,0,
       0,0,0,0,-1,2,-1
       ])
show(A)

[2 4 4 0 0 0 0]
[1 0 2 2 0 0 0]
[1 0 2 2 0 0 0]
[0 0 0 4 2 4 0]
[0 0 0 0 4 2 4]

In [70]:
A.echelon_form()

[1 0 2 0 0 1 1]
[0 1 0 0 0 2 2]
[0 0 0 1 0 2 2]
[0 0 0 0 1 3 1]
[0 0 0 0 0 0 0]

In [71]:
A.smith_form()

(
                              [1 3 2 4 3 4 4]
                              [0 1 4 3 0 3 3]
[1 0 0 0 0 0 0]  [3 0 0 0 0]  [0 0 0 0 1 0 0]
[0 1 0 0 0 0 0]  [4 2 0 0 0]  [0 0 4 3 0 3 3]
[0 0 1 0 0 0 0]  [0 0 0 1 0]  [0 0 0 4 0 2 4]
[0 0 0 1 0 0 0]  [0 0 0 0 1]  [0 0 0 0 0 1 0]
[0 0 0 0 0 0 0], [0 4 1 0 0], [0 0 0 0 0 0 1]
)

In [72]:
print(A.rank())
print(A.nullity())

4
1


In [74]:
A.kernel()

Vector space of degree 5 and dimension 1 over Finite Field of size 5
Basis matrix:
[0 1 4 0 0]

In [75]:
matrix(np.random.randint(9, size=(3,3)))

[6 3 3]
[2 5 4]
[3 5 7]

In [138]:
P.<x> = PolynomialRing(ZZ)
p = P(ZZ[x].random_element(degree=randint(3, 5)))
while p.is_irreducible() or p.gcd(x) != 1:
    p = P(ZZ[x].random_element(degree=randint(3, 5)))
show(p)

2*x^5 + 2*x^3 + 3*x^2 + x + 2

In [139]:
p.change_ring(QQ[x]).factor()

(1) * (x + 1) * (2*x^4 - 2*x^3 + 4*x^2 - x + 2)

In [127]:
p.gcd(x)

1

In [100]:
ZZ[x].gen()

x

In [147]:
var('k')
n = 10
f(k) = binomial(n, k)

f(3)

120

In [163]:
var('x n')
N = 6
f(n) = binomial(N, n) x^n
S = sum(f, n, 0, N)
S

x^6 + 6*x^5 + 15*x^4 + 20*x^3 + 15*x^2 + 6*x + 1

In [164]:
S(1)

64